import:
  - globals/uw2-globals
  - globals/brave-globals
  - catalog/terraform/vpc
  - catalog/terraform/tfstate-backend
  - catalog/terraform/security-groups
  - catalog/terraform/ec2
  - catalog/terraform/build-brave

vars:
  stage: dev1

terraform:
  vars: {}

helmfile:
  vars: {}

components:
  terraform:
    "infra/vpc":
      vars:
        cidr_block: 172.20.0.0/18
